#!/command/with-contenv bash
# shellcheck shell=bash
set -euo pipefail

mkdir -p /mem0/storage

export USER="${USER:-default_user}"
export NEXT_PUBLIC_USER_ID="${NEXT_PUBLIC_USER_ID:-${USER}}"
export NEXT_PUBLIC_API_URL="${NEXT_PUBLIC_API_URL:-/openmemory-api}"
export DATABASE_URL="${DATABASE_URL:-sqlite:////mem0/storage/openmemory.db}"
export QDRANT_HOST="${QDRANT_HOST:-127.0.0.1}"
export QDRANT_PORT="${QDRANT_PORT:-6333}"
export QDRANT__TELEMETRY_DISABLED="${QDRANT__TELEMETRY_DISABLED:-true}"
export OPENAI_API_KEY="${OPENAI_API_KEY-}"

: >/var/run/mem0-aio.env

runtime_env_vars=(
	USER
	NEXT_PUBLIC_USER_ID
	NEXT_PUBLIC_API_URL
	DATABASE_URL
	QDRANT_HOST
	QDRANT_PORT
	QDRANT__TELEMETRY_DISABLED
	OPENAI_API_KEY
	API_KEY
	OLLAMA_BASE_URL
	OLLAMA_HOST
	LLM_PROVIDER
	LLM_MODEL
	LLM_API_KEY
	LLM_BASE_URL
	EMBEDDER_PROVIDER
	EMBEDDER_MODEL
	EMBEDDER_API_KEY
	EMBEDDER_BASE_URL
	EMBEDDER_DIMENSIONS
	CHROMA_HOST
	CHROMA_PORT
	WEAVIATE_CLUSTER_URL
	WEAVIATE_HOST
	WEAVIATE_PORT
	REDIS_URL
	PG_HOST
	PG_PORT
	PG_DB
	PG_USER
	PG_PASSWORD
	MILVUS_HOST
	MILVUS_PORT
	MILVUS_TOKEN
	MILVUS_DB_NAME
	ELASTICSEARCH_HOST
	ELASTICSEARCH_PORT
	ELASTICSEARCH_USER
	ELASTICSEARCH_PASSWORD
	ELASTICSEARCH_USE_SSL
	ELASTICSEARCH_VERIFY_CERTS
	OPENSEARCH_HOST
	OPENSEARCH_PORT
	OPENSEARCH_USER
	OPENSEARCH_PASSWORD
	OPENSEARCH_USE_SSL
	OPENSEARCH_VERIFY_CERTS
	FAISS_PATH
	EXPORT_USER_ID
	EXPORT_APP_ID
	EXPORT_FROM_DATE
	EXPORT_TO_DATE
)

for name in "${runtime_env_vars[@]}"; do
	value="${!name-}"
	if [[ -n ${value} ]]; then
		printf '%s=%q\n' "${name}" "${value}" >>/var/run/mem0-aio.env
	fi
done

chmod 600 /var/run/mem0-aio.env
echo "[mem0-aio] bootstrap complete"
